# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fcdc6b32799867a98fa022754ae57780353b91a53c016cdf1cd4945297e0933c78c6ab5cc31137e15d999fd9991480419af25b23d11da24cff0ad19267a5c50

test:
  secret_key_base: 20bc34ab22983132e617fdfe4a8b560183e50304844356eda9f95b70691772ffd6f57aec6cea920eadfc2af115e3f9f05cb30bb78f8602d6cc87397c5ee95935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
